@apiUrl = http://localhost:3000

POST {{apiUrl}}/users
Content-Type: application/json

{
  "name": "let", 
  "cpf": "12345678901", 
  "password": "12345"
}

###GET USERS 

GET {{apiUrl}}/users


###GET UNIQUE USER
GET {{apiUrl}}/users/12345678901


###Update user
PUT {{apiUrl}}/users/12345678901
Content-Type: application/json

{
  "name": "Truth Name", 
  "password": "12345"
}

###Delete element
DELETE {{apiUrl}}/users/12345678905

